# 第一階段-建置編譯環境&把專案編譯成Web服務
# 指定基礎鏡像
FROM alpine:latest

# 執行安裝的目錄
WORKDIR /usr/blog

# 時區
ENV TZ=Asia/Taipei
RUN echo "${TZ}" > /etc/timezone 
RUN ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime 

# 安裝&更新所需的套件
RUN apk update
RUN apk upgrade --no-cache
RUN apk add --no-cache nodejs npm icu-data-full tzdata bash git openssh pandoc-cli
RUN rm /var/cache/apk/*

# 安裝 hexo
# 把目錄下的程式碼直接復制到容器中
COPY package*.json ./
COPY . .
RUN npm install hexo-cli -g \ 
&& npm install 

# 設置通訊連接埠  
EXPOSE 4000

# 容器啟動時
CMD [ "hexo", "server" ]

