version: '3'
services:
    web:
      restart: always # 跟系統服務一起重啟
      # network_mode: host # 網路: 使用實體機
      ports:
        - 4000:4000
      # 編譯時的設置
      build:
        context: .
        dockerfile: Dockerfile.env