# 第一階段-建置編譯環境&把專案編譯成Web服務
FROM ubuntu:latest AS build-env
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 1-1 安裝 flutter 相依套件
RUN apt-get update
RUN apt-get install -y nodejs npm pandoc
RUN apt-get clean
# 1-2 创建hexo-blog文件夹且设置成工作文件夹
RUN mkdir -p /usr/src/hexo-blog
WORKDIR /usr/src/hexo-blog
# 1-3 复制当前文件夹下面的所有文件到hexo-blog中
COPY . .
# 1-4 安装 hexo-cli
RUN npm install hexo-cli -g && npm install
# 1-5 生成静态文件
RUN hexo cl && hexo g


# 第二階段-配置nginx
FROM nginx:latest
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /usr/share/nginx/html
# 把上一部生成的HTML文件复制到Nginx中
COPY --from=build-env /usr/src/hexo-blog/public /usr/share/nginx/html
EXPOSE 80